spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/FinancesDB
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE