ALTER TABLE incomes
    ADD COLUMN original_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN interest NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN fine NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN discount NUMERIC(19,2) NOT NULL DEFAULT 0;

ALTER TABLE expenses
    ADD COLUMN original_amount NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN interest NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN fine NUMERIC(19,2) NOT NULL DEFAULT 0,
    ADD COLUMN discount NUMERIC(19,2) NOT NULL DEFAULT 0;
